version: "3"

services:
  uam-dev-container:
    image: uam-dev-ui:latest
    container_name: uam-dev-ui
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "58045:3000"
    restart: always
